modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="serversaturday"
version="3.2.2"
displayName="ServerSaturday"
authors="Musician101"
description='''
Plugin based submission for MightyPotato's YouTube series, Server Saturday.
'''
