name: ServerSaturday
main: com.campmongoose.serversaturday.spigot.SpigotServerSaturday
version: ${version}
api-version: '1.15'
commands:
  serversaturday:
    aliases: [ss]
    description: Displays help and plugin info.
  serversaturdaydescription:
    aliases: [ssdescription, ssd]
    description: Change the description of a submission.
    permission: ss.submit
  serversaturdayedit:
    aliases: [ssedit, sse]
    description: Edit a submitted build.
    permission: ss.submit
  serversaturdayfeature:
    aliases: [ssfeature, ssf]
    description: Toggle if a build has been featured.
    permission: ss.feature
  serversaturdaygetrewards:
    aliases: [ssgetrewards, ssgetr]
    description: Receive any rewards that are currently waiting.
    permission: ss.submit
  serversaturdaygivereward:
    aliases: [ssgivereward, ssgr]
    description: Give a player a reward.
    permission: ss.feature
  serversaturdaygoto:
    aliases: [ssgoto, ssg]
    description: Teleport to a build.
    permission: ss.view.goto
  serversaturdaylocation:
    aliases: [sslocation, ssl]
    description: Change the location of a build.
    permission: ss.submit
  serversaturdaynew:
    aliases: [ssnew, ssn]
    description: Register a new build.
    permission: ss.submit
  serversaturdayreload:
    aliases: [ssreload, ssr]
    description: Reload the plugin.
    permission: ss.reload
  serversaturdayremove:
    aliases: [ssremove, ssrem]
    description: Remove a build.
    permission: ss.submit
  serversaturdayrename:
    aliases: [ssrename, ssren]
    description: Rename a submission.
    permission: ss.submit
  serversaturdayresourcepack:
    aliases: [ssresourcepack, ssrp]
    description: Change the recommended resource pack.
    permission: ss.submit
  serversaturdaysubmit:
    aliases: [sssubmit, sss]
    description: Toggle whether you build is ready to be featured or not.
    permission: ss.submit
  serversaturdaysetrewards:
    aliases: [sssetrewards, sssr]
    description: Set the rewards a player gets from having their build featured.
    permission: ss.feature
  serversaturdayview:
    aliases: [ssview, ssv]
    description: View Server Saturday submissions.
    permission: ss.view
  serversaturdayviewdescription:
    aliases: [ssviewdescription, ssvd]
    description: View the description of a build.
    permission: ss.view
  serversaturdayviewresourcepack:
    aliases: [ssviewresourcepack, ssvrp]
    description: View the build's recommended resource pack.
    permission: ss.view

permissions:
  ss.*:
    default: op
    description: Gives access to all ServerSaturday permissions.
    children:
      ss.feature: true
      ss.max_builds: true
      ss.reload: true
      ss.submit: true
      ss.view: true
      ss.view.goto: true
  ss.feature:
    default: op
    description: Gives access to all feature related commands.
  ss.exceed_max_builds:
    default: op
    description: Gives access to exceed the build submission limit.
  ss.reload:
    default: op
    description: Gives access to the SSReload command.
  ss.submit:
    default: true
    description: Gives access to all submit related commands.
  ss.view:
    default: true
    description: Gives access to the SSView and SSViewDescription commands.
  ss.view.goto:
    default: true
    description: Gives access to all view related commands.
    children:
      ss.view: true
